.TH man 1 "23 April, 2020" "4.0" "mkdesktop man page"

.SH NAME
mkdesktop

.SH SYNOPSIS
mkdesktop \- configure a FreeBSD desktop in a jiffy.

.SH DESCRIPTION
If you setup a desktop, for instance KDE, under a fresh FreeBSD
installation by yourself, you will have to do all of the following :

1) Install X (xorg)
.br
2) Install KDE (kde5)
.br
3) Configure the system files under /etc and /boot

If you use the command mkdesktop, it will do all the above on its own,
and a bit more. The application then winds up by setting up any emulation
layers (Wine / Linuxulator) you might wish to use and configuring login
management with SDDM.

mkdesktop also bundles in 2 special functions : stagezero and postproc.

stagezero corresponds to Level 0 and is launched at startup. This stage
caters to setting up the graphics environment for the various graphics
chipsets (Radeon/NVidia/Intel/AMDGPU), pkg's and kld's for which are
configured as needed.

postproc gets automatically invoked when the regular stages have been
processed.  It sets up :

Wine (Windows emulation layer);
Linuxulator (Linux emulation layer);

Configuration of system files :

/etc/fstab
/etc/devfs.conf
/etc/devfs.rules
/etc/rc.conf
/etc/sysctl.conf
/boot/loader.conf.

The final step the postproc function executes is setting up X login
management with SDDM.

Tip : If you regularly install FreeBSD, you will appreciate the
convenience mkdesktop soon becomes.

.SH OPTIONS
--help : Print the man page (same as `man mkdesktop`).

.SH SEE ALSO
desktop-installer(1)

.SH BUGS
No known bugs.

.SH AUTHOR
Manish Jain (bourne.identity@hotmail.com)
