.TH man 1 "30 April, 2020" "4.3" "mkdesktop man page"

.SH NAME
mkdesktop

.SH SYNOPSIS
mkdesktop \- configure a FreeBSD desktop in a jiffy.

.SH DESCRIPTION
If you setup a desktop, for instance KDE, under a fresh FreeBSD
installation by yourself, you will have to do all of the following :

1) Install X (xorg)
.br
2) Install KDE (kde5)
.br
3) Configure the system files under /etc and /boot

If you use the command mkdesktop, it will do all the above on its own,
and a bit more. The application then winds up by configuring login
management with SDDM and setting up any emulation layers (Wine /
Linuxulator) you might wish to use.

mkdesktop bundles in 2 special functions : stagezero and postproc.

stagezero is launched at startup. This function caters to setting up
the graphics environment for the various graphics chipsets
(Radeon/NVidia/Intel/AMDGPU), pkg's and kld's for which are
configured as needed.

The application then performs user management and the actual desktop
installation.

postproc gets automatically invoked at the end once the desktop has been
installed. It sets up :

Wine (Windows emulation layer - optional);
Linuxulator (Linux emulation layer - optional);

Configuration of system files :

/etc/fstab
/etc/devfs.conf
/etc/devfs.rules
/etc/rc.conf
/etc/sysctl.conf
/boot/loader.conf.

Tip : If you regularly install FreeBSD, you will appreciate the
convenience mkdesktop soon becomes.

.SH OPTIONS
--help : Print the man page (same as `man mkdesktop`).

.SH SEE ALSO
desktop-installer(1)

.SH BUGS
mkdesktop is best used in a pristine environment when system files
(e.g. /etc/fstab; /etc/rc.conf) have not yet been modified. Executing
mkdesktop when system files have been modified could lead to
conflicts in existing settings and settings imposed by mkdesktop.

.SH AUTHOR
Manish Jain (bourne.identity@hotmail.com)
