.TH man 1 "06 December 2018" "2.8" "mkdesktop man page"

.SH NAME
mkdesktop

.SH SYNOPSIS
mkdesktop \- configure a FreeBSD desktop in a jiffy.

.SH DESCRIPTION
If you setup a desktop, for instance KDE, under a fresh FreeBSD
installation by yourself, you will have to do all of the following :

1) Install X (xorg)
.br
2) Install KDE (kde5)
.br
3) Configure the system files under /etc and /boot

If you use the command mkdesktop, it will do all the above on its own,
and a bit more if you so desire - it can install (unattended) anything
else you need, and then set up any emulation layers (Wine / Linuxulator)
you might wish to use. It winds up by optionally configuring login
management with SLiM.

If you wish to use GNOME (gnome3) instead of the default desktop kde5,
just launch mkdesktop and wait for it to initialize itself, and then -
when prompted - run the command :

echo "gnome3" > ~/mkdesktop/pkg_list/desktop

In any subsequent run, whatever is the list of packages in the file
~/mkdesktop/pkg_list/desktop overrides the default definition of
desktop. Package list files are newline-separated.

Although you could lump all packages into a single list, breaking up the
list into more stages allows for better, fine-grained control.

By default, 5 stages are considered, in order :

pre_x -> x -> post_x -> desktop -> post_desktop

(Remember that stage lists are colon-separated, unlike package lists
which are newline separated)

pre_x (level 1) presumes there is no X around. The default definition of
this stage is empty, but this is a good place to specify command-line
utilities - wget:cdrecord:vim-console

x (level 2) is the stage for installing the base X system. By default,
this installs just the xorg meta-distribution.

post_x (level 3) is suited for X stuff that is not desktop-specific. The
default definition of this stage is empty, but you can pull in a lot of
stuff - xclip:firefox:virtualbox-ose:libreoffice:smplayer

desktop (level 4) is the stage for the base desktop. If you wish to
install GNOME as the desktop, use gnome3. The default for this stage is
KDE5, which essentially means the meta-package kde5.

(Like stage x, the stage definition for desktop should preferably be as
lean as possible).

post_desktop (level 5) is where you get the stuff that is
desktop-specific. If you chose gnome3-lite as desktop, you can add some
applications at this stage to make your desktop fuller (although the
default setting for this stage is empty) -
gnome-terminal:gedit:gdm:file-roller

Each stage can be defined in one/both of the following 2 ways :

1) list_<stage> is a colon-separated list of packages for the stage. As
you would expect, the default implementation has 5 such lists :
list_pre_x, list_x, list_post_x, list_desktop, list_post_desktop.  These
lists reside in their respective declarations in the file
~/mkdesktop/stage-definitions (specifically the line list_$ident=)

2) If a file named <stage> exists in the package list directory, it
supersedes the definition of list_<stage>. Since the default
implementation is wired for ~/mkdesktop/pkg_list as the package list
directory, this script by default looks for files named pre_x, x,
post_x, desktop and post_desktop therein. You can change the package
list directory location by passing in "--pkg-list-dir <location>"

Unlike the colon-separated stage lists, package list files are
newline-separated. If the first character on a line is '#' (hash without
quotes), the line is ignored as a comment.

mkdesktop also bundles in 2 special functions : stagezero and postproc.

stagezero has to be explicitly invoked by passing in '--begin 0' and it
caters to setting up the graphics environment for Radeon/NVidia
chipsets, kld's for which are set up to be loaded automatically at
boot-time via /etc/rc.local. For NVidia, stagezero also pulls in the
graphics driver nvidia-driver.

postproc gets automatically invoked when the regular stages have been
processed.  It sets up - if the user chooses y[es] for each of these -
Wine (Windows emulation layer); Linuxulator (Linux emulation layer);
configuration of system files :

Under /etc/ : fstab; devfs.conf; devfs.rules; rc.conf; sysctl.conf;
.br
Under /boot/ : loader.conf.

The final step the postproc function executes is optionally setting up
X login management with SLiM.

Tip : it might be a bit painful learning how to use mkdesktop the first
time around. But if you regularly install FreeBSD, you will appreciate
the convenience it soon becomes.

.SH OPTIONS
--begin <level>	: Use <level> as the beginning stage
(default: 1)

--end <level> : Use <level> as the last stage
(default: highest available)

--pkg-list-dir <dir> : Use <dir> as the package list directory
(default: ~/mkdesktop/pkg_list)

--no-postproc : Disable the postproc function that kicks in
automatically upon processing of regular stages to configure emulation
layers and system files

--dry : Test without making changes to the system. --dry is available to
non-root users too, and can be used to print the complete list of
packages (automatic + non-automatic) to be installed / download size.

--echo : Just list the top-level (non-automatic) packages that would be
installed. Regular stage levels get processed through 'echo', not via
the normal route 'pkg install'. --echo takes precedence over --dry, and
is available to non-root users too.

--append : In append mode, packages mentioned in package list files are
appended to the stage definition lists, which otherwise would be
superseded.

--help : Print the man page (same as `man mkdesktop`).

--usage : Print usage information.

.SH SEE ALSO
desktop-installer(1)

.SH BUGS
No known bugs.

.SH AUTHOR
Manish Jain (bourne.identity@hotmail.com)
